### ISSUE TITLE
GammaUtils Incompatibility

### ISSUE THREAD

**Issue by Felix14-v2** [Abbie5/oldpotions#4]
Minecraft crashes after getting an effect with the gamma status effect enabled

# Info:
- Fabric Loader 0.14.18
- Fabric API 0.76.0
- Old Potions 2.1
- [Gamma Utils](https://github.com/Sjouwer/gamma-utils) 1.6.14
- (+ StackDeobfuscator 1.2.0 and Shared Resources 1.5.0)

# Related
[latest.log](https://github.com/Abbie5/oldpotions/files/11056218/latest.log)
[gamma-utils#21](https://github.com/Sjouwer/gamma-utils/issues/21)

**Comment by Sjouwer** [comment]
I believe something like this should solve the issue:
```java
@Inject(method = "getColor", at = @At("HEAD"), cancellable = true)
    private void oldpotions$modifyColor(CallbackInfoReturnable<Integer> cir) {
        if (config.oldColors) {
            int colorIndex = MobEffect.getId((MobEffect) (Object) this) - 1;
            if (colorIndex < colors.length)
                cir.setReturnValue(colors[colorIndex]);
        }
    }
```

**Comment by Abbie5** [comment]
fixed in 2.2

**Comment by Felix14-v2** [comment]
> fixed in 2.2

Crash is still present, even with OldPotions 2.2:

<details>
 <summary>trace</summary>

```
[10:32:34] [Server thread/INFO]: Felix14_v2 joined the game
[10:32:35] [Render thread/INFO]: Loaded 1142 advancements
[10:32:48] [Server thread/INFO]: [Felix14_v2: Applied effect Invisibility to Felix14_v2]
[10:32:48] [Render thread/INFO]: [System] [CHAT] Applied effect Invisibility to Felix14_v2
[10:32:57] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 33
	at net.minecraft.entity.effect.StatusEffect.handler$zkk000$oldpotions$modifyColor(StatusEffect.java:1055) ~[client-intermediary.jar:?]
	at net.minecraft.entity.effect.StatusEffect.getColor(StatusEffect.java) ~[client-intermediary.jar:?]
	at net.minecraft.entity.effect.StatusEffectInstance.compareTo(StatusEffectInstance.java:338) ~[client-intermediary.jar:?]
	at net.minecraft.entity.effect.StatusEffectInstance.compareTo(StatusEffectInstance.java:21) ~[client-intermediary.jar:?]
	at com.google.common.collect.ReverseNaturalOrdering.compare(ReverseNaturalOrdering.java:39) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ReverseNaturalOrdering.compare(ReverseNaturalOrdering.java:26) ~[guava-31.1-jre.jar:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:220) ~[?:?]
	at java.util.Arrays.sort(Arrays.java:1233) ~[?:?]
	at com.google.common.collect.Ordering.sortedCopy(Ordering.java:854) ~[guava-31.1-jre.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.renderStatusEffectOverlay(InGameHud.java:475) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud.java:262) ~[client-intermediary.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:918) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1218) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[Fabric%201.19.4%20%d0%b4%d0%bb%d1%8f%20%d1%82%d0%b5%d1%81%d1%82%d0%be%d0%b2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
```
</details>

[latest.log](https://github.com/Abbie5/oldpotions/files/11797304/latest.log)
[crash-2023-06-20_10.32.58-client.txt](https://github.com/Abbie5/oldpotions/files/11797309/crash-2023-06-20_10.32.58-client.txt)

**Comment by Sjouwer** [comment]
I'm sorry, this is caused by a recent change to my mod: https://github.com/Sjouwer/gamma-utils/commit/cd1ac49b2a0ad49686928d47676aec6cc4589f52
The status effects caused some issues with LAN: https://github.com/Sjouwer/gamma-utils/issues/22
So I had to not actually register them to make them fully client side even with LAN.
This does mean though that the effects won't have an id and will return -1, which causes the same issue here again but now on the other side. Which means the check has to be updated to make sure the colorIndex is also larger than 0.
I hope you're willing to update your mod again @Abbie5, I'm really sorry for the trouble.

@Felix14-v2 you should be able to use the previous Gamma Utils version for now, that one should still work fine as long as you don't play on LAN

**Comment by Abbie5** [comment]
i'll reopen this issue so i remember to update when i have the time
